name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. GitHub repozitoriyasını klonlamaq
      - uses: actions/checkout@v2

      # 2. Node.js qurulması
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 3. Növbəti addımda dependencies (npm) quraşdırılır
      - name: Install dependencies
        run: |
          npm install

      # 4. Playwright testlərini işlətmək
      - name: Run Playwright tests
        run: |
          npx playwright test --reporter=allure-playwright

      # 5. Allure reportu yaratmaq
      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report

      # 6. Allure reportu artifact kimi saxlamaq
      - name: Upload Allure Report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report/

      # 7. Nəticəni GitHub Actions-da açmaq üçün: 
      - name: View Allure Report
        run: |
          npx allure open allure-report